In [99]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Soham\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

#### Challenge 1 – Complete Data Cleaning
#### Your manager gives you a messy dataset.
#### Perform all of the following:
#### • Load the dataset.
#### • Display dataset information.
#### • Find missing values.
#### • Remove duplicate rows.
#### • Fill missing values:
#### o Age → median
#### o Balance → mean
#### • Rename:
#### o Target → CustomerStatus
#### o AnnualIncome → Income
#### • Display the first 15 rows.
#### Methods expected:
#### read_csv()
#### info()
#### isnull()
#### drop_duplicates()
#### median()
#### mean()
#### fillna()
#### rename()
#### head()

In [102]:
pd.read_csv("C:\\Users\\Soham\\Downloads\\Task_dataset - Task_dataset.csv")

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [104]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [106]:
# Find missing values
df.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [108]:
# Remove duplicate rows
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [110]:
# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [112]:
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [114]:
# Rename columns
df.rename(columns={
    "Target": "CustomerStatus",
    "AnnualIncome": "Income"
})

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [116]:
# Display first 15 rows
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

#### Challenge 2 – Banking Report
#### The bank wants a numeric report.
#### Tasks
#### • Select only numeric columns.
#### • Display summary statistics.
#### • Convert Age and CreditScore to float.
#### • Display information again.

In [119]:
df.select_dtypes(include="number")

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
0,10001,58.0,49184.0,2139,581,97523.535666,2
1,10002,65.0,162964.0,6197,732,6356.540000,1
2,10003,56.0,26956.0,37281,503,143203.920000,8
3,10004,55.0,92926.0,925,463,139627.880000,5
4,10005,66.0,108236.0,7198,394,75985.460000,5
...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2
1016,10753,25.0,54490.0,13794,303,124512.070000,4
1017,10810,49.0,82062.0,47170,813,53850.090000,8
1018,10267,38.0,NaN,10424,722,138100.050000,6
1019,10059,62.0,97504.0,36833,430,97523.535666,10

In [121]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,967.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,52303.362541,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,66149.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,158000.500000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [123]:
df["Age"]=df["Age"].astype(float)
df["Age"]
df["CreditScore"]=df["CreditScore"].astype(float)
df["CreditScore"]

0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64

#### Challenge 3 – Duplicate Investigation
#### Find duplicate customers.
#### Then
#### • Count duplicate rows.
#### • Remove duplicates.
#### • Print information before and after removing duplicates.
#### • Show the last 20 rows.

In [126]:
# Dataset information before removing duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [128]:
# Find duplicate rows
df[df.duplicated()]

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1000,10643,41.0,125012.0,18825,761.0,35977.850000,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838.0,115028.540000,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306.0,81892.130000,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484.0,190233.860000,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383.0,168358.600000,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688.0,65481.650000,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598.0,142086.700000,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489.0,29651.230000,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681.0,23880.190000,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643.0,130886.930000,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309.0,60223.290000,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804.0,176354.130000,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413.0,76591.000000,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654.0,132742.130000,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662.0,14415.100000,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [130]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()
duplicate_count

20

In [132]:
# Remove duplicate rows
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [134]:
# Dataset information after removing duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [136]:
# Display last 20 rows
df.tail(20)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1000,10643,41.0,125012.0,18825,761.0,35977.850000,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838.0,115028.540000,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306.0,81892.130000,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484.0,190233.860000,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383.0,168358.600000,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688.0,65481.650000,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598.0,142086.700000,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489.0,29651.230000,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681.0,23880.190000,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643.0,130886.930000,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309.0,60223.290000,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804.0,176354.130000,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413.0,76591.000000,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654.0,132742.130000,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662.0,14415.100000,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

#### Challenge 4 – HR Department
#### HR wants better column names.
#### Rename
#### CustomerID → Employee_ID
#### Age → EmployeeAge
#### AnnualIncome → Salary
#### Target → PromotionStatus
#### Then
#### • Add prefix
#### HR_
#### to every column.
#### Display 10 random records.

In [139]:
# Rename the Columns
df = df.rename(columns={
    "CustomerID": "Employee_ID",
    "Age": "EmployeeAge",
    "AnnualIncome": "Salary",
    "Target": "PromotionStatus"
})
df

,Employee_ID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [141]:
# Add Prefix HR_ to Every Column
df = df.add_prefix("HR_")
df

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_Gender,HR_Segment,HR_PromotionStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644.0,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303.0,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813.0,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722.0,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430.0,97523.535666,10,Canada,Other,NaN,Churn

In [143]:
# Display 10 Random Records
df.sample(10)

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_Gender,HR_Segment,HR_PromotionStatus
241,10242,67.0,53825.0,28852,814.0,182142.45,0,India,Other,Retail,Churn
110,10111,45.0,104494.0,40064,556.0,5172.98,3,France,Other,SME,Churn
879,10880,62.0,107269.0,35294,333.0,59318.00,4,France,Other,SME,Churn
739,10740,65.0,195987.0,13792,509.0,13227.26,7,Germany,Female,SME,Churn
348,10349,65.0,185911.0,32678,889.0,156394.87,5,Canada,Female,Corporate,Stay
85,10086,45.0,193413.0,24785,370.0,101192.16,5,India,Female,Corporate,Churn
618,10619,61.0,33645.0,11034,698.0,192914.05,0,India,Male,Corporate,Churn
862,10863,60.0,31302.0,4040,672.0,57012.90,6,UK,Female,SME,Stay
661,10662,46.0,100705.0,24471,722.0,51961.41,4,India,Male,SME,Stay
933,10934,24.0,67408.0,23753,688.0,84818.37,8,NaN,Female,NaN,Stay

#### Challenge 5 – Finance Cleaning
#### Finance department reports missing values.
#### Tasks
#### Fill
#### AnnualIncome → Median
#### Balance → Mean
#### Age → Median
#### Then
#### Generate descriptive statistics.

In [146]:
# Check missing values
df.isnull().sum()

HR_Employee_ID         0
HR_EmployeeAge         0
HR_Salary             53
HR_Spending            0
HR_CreditScore         0
HR_Balance             0
HR_Tenure              0
HR_Geography          51
HR_Gender             52
HR_Segment            51
HR_PromotionStatus     0
dtype: int64

In [160]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Soham\\Downloads\\Task_dataset - Task_dataset.csv")
df

# Fill missing values
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["AnnualIncome"]
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Balance"]
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [162]:
# Check missing values again
df.isnull().sum()

CustomerID       0
Age              0
AnnualIncome     0
Spending         0
CreditScore      0
Balance          0
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [164]:
# Generate descriptive statistics
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 6 – Data Type Audit
#### The company says
#### Age and AnnualIncome are stored incorrectly.
#### Tasks
#### Convert
#### Age → int
#### AnnualIncome → float
#### Balance → float
#### Target → string
#### Print information.

In [168]:
# # Fill missing values (if any)
# df["Age"] = df["Age"].fillna(df["Age"].median())
# df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
# df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# Convert data types
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

# Print dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int32
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int32(1), int64(4), object(4)
memory usage: 83.8+ KB

#### Challenge 7 – Customer Analytics
#### Create a new DataFrame that
#### • removes Segment
#### • removes Geography
#### • removes duplicate rows
#### Display
#### • first 10 rows
#### • dataset information
#### • statistical summary

In [170]:
new_df = df.drop(columns=["Segment", "Geography"])

new_df = new_df.drop_duplicates()

new_df.head(10)

new_df.info()

new_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int32
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(2), int32(1), int64(4), object(2)
memory usage: 74.2+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112453.288000,25285.558000,603.088000,97555.864273,5.241000
std,288.819436,15.130834,51081.479931,14211.735656,176.605486,54430.062511,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112358.000000,24901.000000,606.500000,97523.535666,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 8 – ML Dataset Preparation
#### Prepare a machine learning dataset.
#### Perform
#### • Remove duplicates
#### • Remove CustomerID
#### • Remove Segment
#### • Fill missing values
#### • Rename Target to Output
#### Finally
#### Display
#### head()
#### info()
#### describe()
#### value_counts(Output)

In [1]:
# Remove duplicate rows
df = df.drop_duplicates()

NameError: name 'df' is not defined

In [ ]:
# Remove unnecessary columns
df = df.drop(columns=["CustomerID", "Segment"])

In [ ]:
# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [ ]:
# Rename Target column
df = df.rename(columns={"Target": "Output"})

In [ ]:
# Display first 5 rows
print(df.head())

In [ ]:
# Display dataset information
df.info()

In [ ]:
# Display statistical summary
print(df.describe())

In [ ]:
# Display Output value counts
print(df["Output"].value_counts())

#### Challenge 9 – Column Transformation
#### Create these new columns
#### NetWorth = Balance + AnnualIncome
#### AgeAfterRetirement = Age + 20
#### DoubleCreditScore = CreditScore * 2
#### IncomePerMonth = AnnualIncome / 12
#### Then
#### Display first 15 rows.

#### Challenge 10 – Company Report
#### Display
#### • first five rows
#### • last five rows
#### • ten random rows
#### • dataset information
#### • descriptive statistics
#### Finally rename
#### Target → Customer_Status

In [ ]:
# Challenge 11 – Missing Value Report
# Create a report showing
# • Total missing values
# • Numerical columns
# • Mean of Balance
# • Median of Age
# • Fill missing values
# • Display information again

In [ ]:
# Challenge 12 – Customer Classification
# Count
# Stay
# Churn
# Then
# Rename
# Target → Customer_Class
# Convert it into string.

In [ ]:
# Challenge 13 – Sales Department
# Rename
# Balance → AccountBalance
# AnnualIncome → Salary
# CreditScore → Score
# Add prefix
# Sales_
# Then
# Display
# sample(20)

In [ ]:
# Challenge 14 – Interview Challenge
# Without creating another DataFrame,
# perform
# • remove duplicates
# • rename Target
# • fill missing values
# • convert Balance to float
# • display summary

In [ ]:
# Challenge 15 – Data Engineer Task
# Load the dataset.
# Create another DataFrame containing only numeric columns.
# Drop
# CustomerID
# Target
# Display summary.

In [ ]:
# Challenge 16 – Mixed Cleaning
# Perform
# drop_duplicates()
# fillna()
# astype()
# rename()
# head()
# info()
# using only one DataFrame variable.

In [ ]:
# Challenge 17 – Real Company Dataset
# Manager asks
# Remove duplicate records
# Fill missing values
# Rename all business columns
# Add company prefix
# Display summary
# Display target counts

In [ ]:
# Challenge 18 – Customer Summary
# Generate
# Mean Balance
# Median Balance
# Mean Age
# Median AnnualIncome
# Then
# fill missing values using these statistics.

In [ ]:
# Challenge 19 – Transformation Challenge
# Create
# Income_in_Lakhs
# Balance_in_Lakhs
# SeniorCitizen
# HighCreditScore
# where
# SeniorCitizen = Age + 0
# HighCreditScore = CreditScore * 1
# (No conditional statements.)

In [ ]:
# Challenge 20 – Final Interview Project
# Your manager gives you a dirty customer dataset.
# Prepare the final dataset.
# Requirements
# Load dataset
# Check information
# Find missing values
# Remove duplicates
# Rename
# CustomerID
# AnnualIncome
# CreditScore
# Target

# Convert
# Age
# AnnualIncome
# Balance

# Fill missing values
# Remove
# Segment
# CustomerID

# Create new columns
# TotalMoney = Balance + AnnualIncome
# AgeAfter5Years = Age + 5
# MonthlyIncome = AnnualIncome / 12
# CreditScoreDouble = CreditScore * 2Display
# • Head
# • Tail
# • Sample
# • Describe
# • Target counts
# • Final information