In [84]:
import pandas as pd

In [86]:
df = pd.read_csv("C:\\Users\\Soham\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Allowed methods only:
#### pd.DataFrame(), pd.read_csv(), head(), tail(), sample(), info(), isnull(), isna(), select_dtypes(),
#### describe(), drop(), duplicated(), drop_duplicates(), value_counts(), rename(), add_prefix(),
#### astype(), fillna(), mean(), median()

#### Easy Level (1–10)
#### Q1
#### Load the dataset and display the first 10 records.

In [90]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

#### Q2
#### Display the last 15 customers.

In [93]:
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Q3
#### Show 7 random customer records.

In [95]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5360,5361,15661349,Perkins,633,France,Male,35,10,0.00,2,1,0,65675.47,0
4688,4689,15669606,Chu,690,France,Male,33,5,0.00,2,1,0,138017.68,0
1958,1959,15737506,Tretiakova,645,France,Male,42,6,0.00,1,0,0,149807.01,0
6039,6040,15768887,Hsing,597,Spain,Male,26,5,0.00,2,0,1,95159.13,0
562,563,15665678,Tan,607,Spain,Male,36,8,158261.68,1,1,1,76744.72,0
8173,8174,15568032,Moore,757,Germany,Male,31,1,127320.36,3,1,0,163170.32,0
3262,3263,15654456,Napolitano,511,Germany,Male,48,6,149726.08,1,0,0,88307.87,1

#### Q4
#### Print complete dataset information and identify:
#### • Total columns
#### • Data type of each column
#### • Missing values

In [97]:
# 1. df.info()

# Displays complete information about the dataset.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [98]:
# 2. Total Columns

len(df.columns)

14

In [99]:
# 3. Data Type of Each Column

print(df.dtypes)

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [100]:
# 4. Missing Values

print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

#### Q5
#### Find missing values in every column.

In [102]:
# Find missing values in every column
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

#### Q6
#### Display only numerical columns.

In [111]:
# Display only numerical columns

df.select_dtypes(include='number')

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

#### Q7
#### Generate the statistical summary of numerical columns.

In [113]:
# Generate statistical summary
print(df.describe())

         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

       EstimatedSalary        Exited
count     10000.000000  10000.000000
mean     100090.239881      0.203700
std       57510.492818      0.402769
min          11.580000      0.000000
25%       51002.110000      0.000000
50%      100193.915000      0.000000
75%      149388.247500      0.000000
max      199992.480000      1.000000

#### Q8
#### Find duplicate rows and print how many exist.

In [115]:

# Find duplicate rows
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

#### Q9
#### Remove duplicate rows and store the cleaned dataset.

In [117]:
# Remove duplicate rows
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Q10
#### Count how many customers have exited and how many have not exited.

In [119]:
# Count customers who exited and who did not exit

df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

#### Medium Level (11–20)
#### Q11
#### Rename the following columns:
#### CustomerId → Customer_ID
#### CreditScore → Credit_Score
#### EstimatedSalary → Salary
#### Exited → Churn

In [121]:
# Rename columns
df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Churn"
})

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Q12
#### Add the prefix
#### Bank_
#### to every column name.

In [123]:
# Add prefix 'Bank_' to every column name
df.add_prefix("Bank_")

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Q13
#### Convert the Age column into float datatype.

In [132]:
# Convert Age column to float
df["Age"].astype(float)

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [134]:
# Display the datatype
df["Age"].dtype

dtype('int64')

#### Q14
#### Convert the Exited column into string datatype.

In [137]:
# Convert Exited column to string
df["Exited"].astype(str)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: object

In [139]:
# Display the datatype
df["Exited"].dtype

dtype('int64')

#### Q15
#### Suppose the Balance column has missing values.
#### Replace them using the mean of the Balance column.

In [142]:
# Replace missing values in Balance with the mean
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# Display the updated Balance column
print(df["Balance"])

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [144]:
df["Balance"].describe()

count     10000.000000
mean      76485.889288
std       62397.405202
min           0.000000
25%           0.000000
50%       97198.540000
75%      127644.240000
max      250898.090000
Name: Balance, dtype: float64

#### Q16
#### Suppose the Age column has missing values.
#### Replace them using the median age.

In [146]:
# Replace missing values in Age with the median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Display the updated Age column
print(df["Age"])

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

#### Q17
#### Display only the first five rows after renaming the columns.

In [153]:
# Rename the columns
df = df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Churn"
})

In [155]:
# Display the first five rows
print(df.head())

   RowNumber  Customer_ID   Surname  Credit_Score Geography  Gender  Age  \
0          1     15634602  Hargrave           619    France  Female   42
1          2     15647311      Hill           608     Spain  Female   41
2          3     15619304      Onio           502    France  Female   42
3          4     15701354      Boni           699    France  Female   39
4          5     15737888  Mitchell           850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0       2       0.00              1          1               1  101348.88
1       1   83807.86              1          0               1  112542.58
2       8  159660.80              3          1               0  113931.57
3       1       0.00              2          0               0   93826.63
4       2  125510.82              1          1               1   79084.10

   Churn
0      1
1      0
2      1
3      0
4      0

#### Q18
#### Create a new DataFrame by dropping these columns:
#### RowNumber
#### CustomerId
#### Surname
#### Display the first 10 rows.

#### Q19
#### Drop the Geography column and display dataset information again.

#### Q20
#### Rename NumOfProducts to Products and HasCrCard to CreditCard.

#### Hard Level (21–30)
#### Q21 (Real Company Task)
#### Your manager wants cleaner column names.
#### Rename every column as follows:
#### RowNumber → Row_No
#### CustomerId → Customer_ID
#### Surname → Last_Name
#### CreditScore → Credit_Score
#### Geography → Country
#### Gender → Sex
#### EstimatedSalary → Salary
#### Exited → Target
#### Display the first five rows.

#### Q22
#### Create a new DataFrame that contains only numeric columns.
#### Then generate its statistical summary.

#### Q23
#### Your company received duplicate customer records.
#### Tasks:
#### • Count duplicates.
#### • Remove duplicates.
#### • Display dataset information after cleaning.

#### Q24
#### Management wants every column name to begin with
#### Customer_#### 
#### Apply this transformation using the appropriate method.

#### Q25
#### After renaming the columns, convert
#### Age
#### Balance
#### Salary
#### to float datatype.
#### Print dataset information.

#### Q26
#### Assume CreditScore contains missing values.
#### Replace them with the median CreditScore.

#### Q27
#### Assume EstimatedSalary contains missing values.
#### Replace them with the mean salary.
#### Then print the first eight rows.

#### Q28 (Data Cleaning Challenge)
#### Perform all the following:
#### • Remove duplicate rows.
#### • Rename Exited to Target.
#### • Convert Target to string.
#### • Display dataset information.

#### Q29 (Transformation Challenge)
#### Create a copy of the dataset.
#### Perform these transformations:
#### • Rename Gender to CustomerGender
#### • Rename Geography to Country
#### • Add prefix Bank_
#### • Remove RowNumber
#### • Display first 10 rows

#### Q30 Real Industry Mini Project
#### Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
#### Perform all of these steps:
#### 1. Load the dataset.
#### 2. Display dataset information.
#### 3. Check missing values.
#### 4. Remove duplicate rows.
#### 5. Rename the following columns:
#### o CustomerId → Customer_ID
#### o CreditScore → Credit_Score
#### o EstimatedSalary → Salary
#### o Exited → Target
#### 6. Convert:
#### o Age → float
#### o Balance → float
#### o Target → string
#### 7. Replace missing values:
#### o Age → median
#### o Balance → mean
#### 8. Remove:
#### o RowNumber