In [28]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Soham\\Downloads\\customer_data - customer_data.csv")
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

#### 1. Load the CSV using Pandas and display the first 10 rows.

In [32]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Soham\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

#### 2. Check the number of rows and columns in the dataset.

In [34]:
df.shape

(2000, 15)

#### 3. Display all column names and identify which column names contain leading/trailing spaces or inconsistent capitalization.

In [38]:
df.columns

Index(['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [62]:
for col in df.columns:
    if col != col.strip():
        print("Space problem:", repr(col))

In [64]:
for col in df.columns:
    print(repr(col))

print("\nColumns with leading/trailing spaces:")

for col in df.columns:
    if col != col.strip():
        print(repr(col))

print("\nColumn names in lowercase for capitalization checking:")

for col in df.columns:
    print(col, "->", col.lower())

'Customer ID'
'Age'
'income_usd'
'credit Score'
'tenure_years'
'monthly_visits'
'satisfaction'
'City'
'customer_segment'
'gender'
'is_active'
'churn_flag'
'signup_date'
'lead_source'
'notes_text'

Columns with leading/trailing spaces:

Column names in lowercase for capitalization checking:
Customer ID -> customer id
Age -> age
income_usd -> income_usd
credit Score -> credit score
tenure_years -> tenure_years
monthly_visits -> monthly_visits
satisfaction -> satisfaction
City -> city
customer_segment -> customer_segment
gender -> gender
is_active -> is_active
churn_flag -> churn_flag
signup_date -> signup_date
lead_source -> lead_source
notes_text -> notes_text

#### 4. Check the data type of every column using Pandas.

In [67]:
df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

#### 5. Calculate the number and percentage of missing values in every column.

In [70]:
df.isnull().sum()

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

#### 6. Find the rows where Customer ID is missing.

In [73]:
df['Customer ID'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Customer ID, Length: 2000, dtype: bool

#### 7. Remove leading/trailing whitespace from all column names and convert them to lowercase with underscores.

In [77]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

#### 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [79]:
duplicate_ids = df['customer_id'].value_counts()
duplicate_ids = duplicate_ids[duplicate_ids > 1]

print(duplicate_ids)
print("Number of duplicate Customer IDs:", len(duplicate_ids))

Series([], Name: count, dtype: int64)
Number of duplicate Customer IDs: 0

#### 9. Remove duplicate customer records while keeping the first occurrence.

In [91]:
df.drop_duplicates(subset='customer_id', keep='first')

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

#### 10.Find all unique values in the customer_segment column and identify inconsistent categories such as Consumer, consumer, consumer , etc.

In [85]:
print(df['customer_segment'].unique())

['consumer' 'Consumer' 'Enterprise' 'SMB' nan 'SMB.' 'UNKNOWN']

In [87]:
print(df['customer_segment'].value_counts())

customer_segment
Consumer      661
SMB           390
Enterprise    290
consumer      118
UNKNOWN        76
SMB.           68
Name: count, dtype: int64

In [89]:
print(df['customer_segment'].str.strip().str.lower().unique())

['consumer' 'enterprise' 'smb' nan 'smb.' 'unknown']

#### 11.Clean the customer_segment column by standardizing capitalization and whitespace.

In [99]:
df['customer_segment'].str.strip().str.lower()

0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 1981, dtype: object

#### 12.Find all unique values in the gender column and convert them into consistent categories such as Male and Female.

In [101]:
df['gender'].str.strip().str.lower().str.title()

0        NaN
1       Male
2          M
3          M
4       Male
        ...
1995       M
1996       M
1997       F
1998     NaN
1999     NaN
Name: gender, Length: 1981, dtype: object

#### 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0.

In [105]:
df['is_active'].astype(str).str.strip().str.lower()

0         1
1       nan
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 1981, dtype: object

In [109]:
df['is_active'].replace({
    'yes': 1,
    'y': 1,
    '1': 1,
    'no': 0,
    'n': 0,
    '0': 0
})

0         1
1       nan
2         1
3         0
4         1
       ...
1995      0
1996      0
1997      1
1998      0
1999      1
Name: is_active, Length: 1981, dtype: object

#### 14.Convert the churn_flag column from categorical values (Yes/No) into a binary numerical column (1/0).

In [125]:
df['churn_flag'].replace({ 'Yes': 1, 'No': 0})

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag, Length: 1981, dtype: float64

#### 15.Identify all values in income_usd that cannot be directly interpreted as numbers.

In [117]:
df[pd.to_numeric(df['income_usd'], errors='coerce').isna()]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,smb,Male,1,1.0,21/07/2024,NaN,follow-up needed
10,CUST-00057,NaN,"$41,941",564.1603365,2.797453,9.0,3.616870,Chennai,enterprise,M,0,1.0,2021-02-27,NaN,complaint!!!
11,CUST-01293,NaN,NaN,744.4081339,6.966279,1.0,3.990252,Bengaluru,smb,F,1,0.0,09/08/2024,Website,???
13,CUST-00585,NaN,NaN,NaN,2.786554,8.0,NaN,Mumbai,smb,m,1,0.0,19/08/2022,referral,???
18,CUST-01647,36.56997395,NaN,795.7311323,12.149658,6.0,NaN,Pune,NaN,m,1,0.0,2025-08-05,website,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1980,CUST-00131,33.32228236,"$58,046",NaN,0.892336,3.0,5.000000,Mumbai,consumer,Female,1,1.0,2021-05-13,???,late payment
1985,CUST-00088,38.14992942,NaN,712.2153889,2.553774,8.0,4.180238,Delhi,consumer,f,0,0.0,2021-03-30,NaN,NaN
1989,CUST-00467,NaN,NaN,603.905614,3.606269,7.0,3.139857,Bengaluru,smb,f,1,0.0,2022-04-20,Email,NaN
1990,CUST-00122,40.15130762,NaN,762.6314638,4.773822,3.0,4.206313,Bengaluru,consumer,f,0,0.0,2021-05-04,???,urgent
1991,CUST-01639,38.09938292,NaN,695.4550712,7.359587,5.0,2.643149,Kolkata,consumer,Male,0,1.0,2025-07-28,Unknown,NaN

#### 16.Clean income_usd by removing currency symbols, commas, and invalid text, then convert it to a numeric column using pd.to_numeric().

In [121]:
df['income_usd'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 1981, dtype: object

In [123]:
pd.to_numeric(df['income_usd'], errors='coerce')

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 1981, dtype: float64

#### 17.Clean the Age column so values such as "35 years" become numeric values.

In [137]:
df['age'].astype(str).str.replace(' years', '', regex=False)

0       45.86741673
1       47.76516428
2               nan
3       62.72357805
4               nan
           ...
1995    27.26951178
1996    41.09168505
1997    26.21576696
1998           42.3
1999    59.25609491
Name: age, Length: 1981, dtype: object

In [141]:
pd.to_numeric(df['age'], errors='coerce')

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1981, dtype: float64

#### 18.Identify unrealistic age values using NumPy/Pandas and replace them with NaN.

In [178]:
import numpy as np

df = df.copy()

df['age'] = pd.to_numeric(df['age'], errors='coerce')

df.loc[~df['age'].between(18, 100), 'age'] = np.nan

print(df['age'])

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1981, dtype: float64

#### 19.Clean the credit_score column by removing text such as "pts" and converting the column to numeric.

In [164]:
df['credit_score'].astype(str).str.replace('pts', '', regex=False)

0       660.5629176
1             838.0
2       613.1327754
3       720.2369862
4       549.1832523
           ...
1995    633.9740063
1996    701.7201056
1997    647.7993363
1998          521.0
1999    576.7390735
Name: credit_score, Length: 1981, dtype: object

In [166]:
pd.to_numeric(df['credit_score'], errors='coerce')

0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit_score, Length: 1981, dtype: float64

#### 20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

#### 21.Detect outliers in credit_score using the IQR method.

#### 22.Detect suspicious values such as -999 and 99999 in tenure_years and satisfaction.

#### 23.Replace invalid/suspicious numerical values with NaN.

#### 24.Fill missing numerical values using the median of each numerical column.

#### 25.Fill missing categorical values using the mode of each categorical column.