#### Part 1 — Inspect & Understand the Dataset
#### Q1. Load the dataset
#### Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#### Then display the first 10 rows.
#### Use: pd.read_csv(), head()

In [99]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Soham\\Downloads\\customer_analytics - customer_analytics.csv")
print(df)
df.head(10)

      Unnamed: 0.1  Unnamed: 0  Customer_ID   Age  Annual_Income  \
0                0           0       101317  55.0        44033.0
1                1           1       101001  32.0       215546.0
2                2           2       101069  23.0       226403.0
3                3           3       101968  66.0        87824.0
4                4           4       100530  67.0        31570.0
...            ...         ...          ...   ...            ...
1995          1995        2035       101131  42.0        88530.0
1996          1996        2036       101295  31.0       205738.0
1997          1997        2037       100861  25.0       211994.0
1998          1998        2038       101460  64.0        30105.0
1999          1999        2039       101127  55.0       248332.0

      Account_Balance  Credit_Score  Tenure_Years       City    Segment  \
0           111350.85         772.0             3  Bangalore        SME
1           254378.37         374.0             8      Delhi     Retail
2           159975.42         668.0            12    Chennai    Premium
3           295741.60         315.0            14     Mumbai    Premium
4           242423.78         370.0             4  bangalore     Retail
...               ...           ...           ...        ...        ...
1995        153490.72         677.0            12  Hyderabad     Retail
1996        270989.40         392.0             8     Mumbai  Corporate
1997        160507.65         737.0             8    Kolkata     Retail
1998         32117.15         794.0             8  Bangalore     Retail
1999        274980.99         783.0             6    Chennai     Retail

     Channel   Join_Date Active Risk_Level  Monthly_Spend  Transactions  \
0      Agent  2022-08-15    Yes        Low       23066.19           135
1      Agent  2025-01-11    Yes       High       24625.17           106
2      Agent  2024-08-01     No     Medium       28536.34           146
3      Agent  2021-05-15    Yes       High       12869.71           115
4      Agent  2026-02-03     No       High       34163.02            94
...      ...         ...    ...        ...            ...           ...
1995   Agent  2021-07-10     No     Medium        8455.42           119
1996   Agent  2025-07-05    Yes       High       34087.69           134
1997  Online  2022-10-17    Yes        Low       26518.74            87
1998   Agent  2023-08-26     No        Low       20943.11           107
1999  Branch  2023-08-24    Yes        Low       48511.32           119

      Satisfaction_Score
0                    3.1
1                    8.2
2                    6.3
3                    9.7
4                    3.7
...                  ...
1995                 8.6
1996                 2.6
1997                 1.3
1998                 9.3
1999                 3.1

[2000 rows x 17 columns]

,Unnamed: 0.1,Unnamed: 0,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,0,0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,1,1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,2,2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,3,3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,4,4,100530,67.0,31570.0,242423.78,370.0,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
5,5,5,101334,68.0,37087.0,180084.44,738.0,1,Chennai,Premium,Agent,2023-06-04,Yes,Low,15121.16,6,8.5
6,6,6,100415,47.0,67229.0,99629.81,464.0,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31,2.8
7,7,7,100983,65.0,139914.0,61030.94,554.0,15,Kolkata,SME,Agent,2024-06-26,Yes,Medium,1720.85,139,9.7
8,8,8,100417,63.0,153267.0,221707.97,508.0,5,Hyderabad,Premium,Mobile,2025-03-12,Yes,High,38043.07,76,7.1
9,9,9,101472,42.0,139914.0,41126.84,556.0,3,Kolkata,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124,9.1

#### Q2. Inspect the end of the dataset
#### Display the last 15 rows.
#### Use: tail()

In [8]:
df.tail(15)

,Unnamed: 0.1,Unnamed: 0,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1985,1985,2025,100088,51.0,214004.0,173779.91,686.0,6,Pune,Premium,Branch,2022-04-22,Yes,Medium,39764.87,85,4.9
1986,1986,2026,101483,47.0,117573.0,261905.82,657.0,2,Pune,NaN,Branch,2022-07-02,Yes,Medium,39559.16,7,1.9
1987,1987,2027,100331,54.0,123511.0,280896.35,388.0,5,Pune,Premium,Mobile,2024-09-11,No,High,24625.17,48,6.7
1988,1988,2028,101239,31.0,125500.0,189174.28,846.0,11,Delhi,Corporate,Agent,2022-04-08,Yes,Low,22161.09,102,8.5
1989,1989,2029,100467,47.0,101619.0,279182.04,392.0,3,Bangalore,Retail,Mobile,2023-07-26,Yes,High,37316.48,100,7.3
1990,1990,2030,100122,41.0,201611.0,40736.71,507.0,15,Bangalore,SME,Agent,2024-11-03,Yes,High,18815.18,58,7.2
1991,1991,2031,101639,61.0,128850.0,266135.80,840.0,9,Kolkata,SME,Mobile,2026-01-15,Yes,Low,34300.44,83,5.0
1992,1992,2032,101045,33.0,88037.0,129948.93,449.0,8,Mumbai,Premium,Mobile,2022-11-30,Yes,High,24625.17,147,9.7
1993,1993,2033,101725,43.0,122756.0,36633.45,487.0,8,Pune,NaN,Mobile,2021-07-04,No,High,10165.71,14,6.4
1994,1994,2034,101096,18.0,189232.0,235131.72,306.0,10,hyderabad,SME,Mobile,2025-09-10,No,High,27227.44,85,5.9
1995,1995,2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
1996,1996,2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
1997,1997,2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
1998,1998,2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
1999,1999,2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

#### Q3. Random inspection
#### Display 10 random records.
#### Use: sample()

In [10]:
df.sample(10)

,Unnamed: 0.1,Unnamed: 0,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1789,1789,1827,100682,66.0,32151.0,234651.38,643.0,0,Mumbai,SME,Branch,2026-03-11,Yes,Medium,26919.17,133,4.6
1772,1772,1810,101249,67.0,133255.0,233041.00,493.0,12,Delhi,Corporate,Online,2023-05-29,No,High,35593.23,93,4.2
855,855,871,100875,45.0,29895.0,213888.00,745.0,9,Mumbai,Retail,Mobile,2023-04-15,No,Low,1606.17,23,7.1
1633,1633,1669,101875,50.0,187727.0,41404.65,429.0,0,Mumbai,NaN,Mobile,2022-11-15,No,High,36597.16,14,3.3
6,6,6,100415,47.0,67229.0,99629.81,464.0,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31,2.8
577,577,587,101324,50.0,44873.0,171966.96,540.0,5,Mumbai,SME,Agent,2023-04-05,No,High,27122.97,129,5.7
442,442,447,101764,57.0,109246.0,141285.02,416.0,5,Bangalore,SME,Mobile,2023-03-25,0,High,13640.92,30,6.9
1775,1775,1813,101497,47.0,139914.0,67882.58,330.0,6,NaN,SME,Agent,2024-01-09,Yes,High,34082.12,141,1.2
1108,1108,1130,101331,57.0,245894.0,176679.92,833.0,4,Mumbai,NaN,Branch,2023-08-24,Yes,Low,7094.72,55,5.9
1220,1220,1244,100909,50.0,220684.0,156479.82,525.0,5,Delhi,Retail,Branch,2025-06-27,Yes,High,7443.23,119,3.3

#### Q4. Dataset audit
#### Use info() to identify:
#### • Number of rows
#### • Number of columns
#### • Columns with missing values
#### • Columns having incorrect/object datatypes
#### Use: info()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0.1        2000 non-null   int64
 1   Unnamed: 0          2000 non-null   int64
 2   Customer_ID         2000 non-null   int64
 3   Age                 2000 non-null   float64
 4   Annual_Income       2000 non-null   float64
 5   Account_Balance     2000 non-null   float64
 6   Credit_Score        2000 non-null   float64
 7   Tenure_Years        2000 non-null   int64
 8   City                1920 non-null   object
 9   Segment             1900 non-null   object
 10  Channel             2000 non-null   object
 11  Join_Date           2000 non-null   object
 12  Active              1942 non-null   object
 13  Risk_Level          2000 non-null   object
 14  Monthly_Spend       2000 non-null   float64
 15  Transactions        2000 non-null   int64
 16  Satisfaction_Score  2000 non-null   float64
dtypes: float64(6), int64(5), object(6)
memory usage: 265.8+ KB

#### Q5. Missing-value audit
#### Calculate the number of missing values in every column.
#### Then verify the result using both:
#### isnull()#### 
#### and
#### isna()

In [17]:
df.isnull().sum()

Unnamed: 0.1            0
Unnamed: 0              0
Customer_ID             0
Age                     0
Annual_Income           0
Account_Balance         0
Credit_Score            0
Tenure_Years            0
City                   80
Segment               100
Channel                 0
Join_Date               0
Active                 58
Risk_Level              0
Monthly_Spend           0
Transactions            0
Satisfaction_Score      0
dtype: int64

#### Part 2 — Detect & Fix Data Quality Problems
#### Q6. Duplicate investigation
#### Find how many duplicate rows exist.
#### Do not remove them yet.
#### Use: duplicated()

In [20]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

#### Q7. Remove duplicates
#### Remove all duplicate records and store the cleaned result back into df.
#### Then verify that duplicates no longer exist.
#### Use: drop_duplicates(), duplicated()

In [23]:
df.drop_duplicates()

,Unnamed: 0.1,Unnamed: 0,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,0,0,101317,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,1,1,101001,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,2,2,101069,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,3,3,101968,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,4,4,100530,67.0,31570.0,242423.78,370.0,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,2035,101131,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
1996,1996,2036,101295,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
1997,1997,2037,100861,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
1998,1998,2038,101460,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
1999,1999,2039,101127,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

In [25]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

#### Q8. Numeric column investigation
#### Select only numeric columns.
#### Identify which columns are currently numeric and which potentially numeric columns have
#### become object because of invalid values.
#### Use: select_dtypes()

In [28]:
df = df.select_dtypes(include="number")
df.columns
df.head()

,Unnamed: 0.1,Unnamed: 0,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,Monthly_Spend,Transactions,Satisfaction_Score
0,0,0,101317,55.0,44033.0,111350.85,772.0,3,23066.19,135,3.1
1,1,1,101001,32.0,215546.0,254378.37,374.0,8,24625.17,106,8.2
2,2,2,101069,23.0,226403.0,159975.42,668.0,12,28536.34,146,6.3
3,3,3,101968,66.0,87824.0,295741.60,315.0,14,12869.71,115,9.7
4,4,4,100530,67.0,31570.0,242423.78,370.0,4,34163.02,94,3.7

#### Q9. Fix Age
#### The Age column contains:
#### • Valid numbers
#### • Missing values
#### • Invalid text such as unknown, N/A, etc.
#### Convert Age into a proper numeric column.
#### Invalid values should become missing values.
#### Then fill missing Age values using the median age.
#### Use: pd.to_numeric(), median(), fillna()

In [39]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Soham\\Downloads\\customer_analytics - customer_analytics.csv")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"]

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
1995    42.0
1996    31.0
1997    25.0
1998    64.0
1999    55.0
Name: Age, Length: 2000, dtype: float64

In [41]:
df["Age"].median()

47.0

In [43]:

df["Age"].dtype

dtype('float64')

In [45]:
df["Age"].dtype

dtype('float64')

#### Q10. Fix Annual Income
#### Clean Annual_Income.
#### Requirements:
#### 1. Convert invalid values to missing.
#### 2. Convert the column to a numeric datatype.
#### 3. Calculate the median.
#### 4. Fill missing values using the median.
#### Use: pd.to_numeric(), median(), fillna(), astype()

In [48]:
df["Annual_Income"]= pd.to_numeric(df["Annual_Income"], errors="coerce")

df["Annual_Income"]= df["Annual_Income"].astype(float)

median= df["Annual_Income"].median()

df["Annual_Income"]= df["Annual_Income"].fillna(median)

df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
1995     88530.0
1996    205738.0
1997    211994.0
1998     30105.0
1999    248332.0
Name: Annual_Income, Length: 2000, dtype: float64

#### Part 3 — Numerical Cleaning
#### Q11. Clean Account Balance
#### The Account_Balance column contains invalid strings and missing values.
#### Clean the column and replace missing values with the mean Account Balance.
#### Use:
#### • pd.to_numeric()
#### • mean()
#### • fillna()

In [51]:
df["Annual_Income"]= pd.to_numeric(df["Annual_Income"], errors="coerce")
mean= df["Annual_Income"].mean()
df["Annual_Income"]= df["Annual_Income"].fillna(mean)
df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
1995     88530.0
1996    205738.0
1997    211994.0
1998     30105.0
1999    248332.0
Name: Annual_Income, Length: 2000, dtype: float64

#### Q12. Clean Credit Score
#### Clean Credit_Score.
#### Invalid values should become missing.
#### Then replace missing values with the median Credit Score.
#### Finally convert the column to integer.
#### Use:
#### • pd.to_numeric()
#### • median()
#### • fillna()
#### • astype()

In [54]:
df["Credit_Score"] =pd.to_numeric(df["Credit_Score"], errors="coerce")
df["Credit_Score"] =df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Credit_Score"] =df["Credit_Score"].astype(int)
df["Credit_Score"]

0       772
1       374
2       668
3       315
4       370
       ...
1995    677
1996    392
1997    737
1998    794
1999    783
Name: Credit_Score, Length: 2000, dtype: int32

#### Q13. Clean Monthly Spend
#### Clean Monthly_Spend.
#### Then:
#### • Convert it to numeric.
#### • Replace invalid values.
#### • Replace missing values using the median.
#### • Make sure the final column is numeric.

In [57]:
df["Monthly_Spend"] =pd.to_numeric(df["Monthly_Spend"], errors="coerce")
df["Monthly_Spend"] =df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())
df["Monthly_Spend"] =df["Monthly_Spend"].astype(float)
df["Monthly_Spend"]

0       23066.19
1       24625.17
2       28536.34
3       12869.71
4       34163.02
          ...
1995     8455.42
1996    34087.69
1997    26518.74
1998    20943.11
1999    48511.32
Name: Monthly_Spend, Length: 2000, dtype: float64

#### Q14. Clean Transactions
#### The Transactions column contains invalid strings.
#### Convert it to numeric and replace invalid values with the median number of transactions.
#### Then convert the final column to integer.

In [60]:
df["Transactions"] =pd.to_numeric(df["Transactions"], errors="coerce")
df["Transactions"] =df["Transactions"].fillna(df["Transactions"].median())
df["Transactions"] =df["Transactions"].astype(int)
df["Transactions"]

0       135
1       106
2       146
3       115
4        94
       ...
1995    119
1996    134
1997     87
1998    107
1999    119
Name: Transactions, Length: 2000, dtype: int32

#### Q15. Clean Satisfaction Score
#### Clean Satisfaction_Score.
#### Replace missing/invalid values using the mean Satisfaction Score.
#### Then convert the column to float.

In [63]:
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"], errors="coerce")

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(df["Satisfaction_Score"].mean())

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
1995    8.6
1996    2.6
1997    1.3
1998    9.3
1999    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64

#### Part 4 — Date Cleaning
#### Q16. Investigate Join_Date
#### Inspect the Join_Date column.
#### Identify the problems caused by:
#### • Missing dates
#### • Different date formats
#### • Invalid date strings
#### Do not clean it yet.

In [66]:
print("Datatype:", df["Join_Date"].dtype)
print("Missing values:", df["Join_Date"].isna().sum())
print("Unique values:")
print(df["Join_Date"].dropna().unique())

Datatype: object
Missing values: 0
Unique values:
['2022-08-15' '2025-01-11' '2024-08-01' ... '2025-09-10' '2022-10-17'
 '2023-08-26']

#### Q17. Convert Join_Date
#### Convert Join_Date into a proper Pandas datetime column.
#### Any invalid dates should become missing values.
#### Use: pd.to_datetime()

In [69]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce",
    dayfirst=True
)

print(df["Join_Date"])
print(df["Join_Date"].dtype)

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
1995   2021-07-10
1996   2025-07-05
1997   2022-10-17
1998   2023-08-26
1999   2023-08-24
Name: Join_Date, Length: 2000, dtype: datetime64[ns]
datetime64[ns]

C:\Users\Soham\AppData\Local\Temp\ipykernel_13488\2328227158.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Join_Date"] = pd.to_datetime(

#### Q18. Handle missing dates
#### After conversion, find how many missing dates remain.
#### Then replace missing dates appropriately using a reasonable date-based strategy.

In [72]:
print(df["Join_Date"].isna().sum())
df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())

0

#### Part 5 — Categorical Cleaning
#### Q19. Clean City
#### The City column contains values such as:
#### Mumbai
#### mumbai
#### Mumbai
#### mumbai
#### Standardize the values so that logically identical cities are represented consistently.
#### Then check the unique frequency distribution.
#### Use: replace(), value_counts()

In [75]:
df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai"
})

print(df["City"].value_counts())

City
Mumbai       308
Hyderabad    274
Delhi        268
Kolkata      260
Pune         253
Chennai      234
Bangalore    230
hyderabad     18
bangalore     17
pune          17
delhi         15
kolkata       14
chennai       12
Name: count, dtype: int64

#### Q20. Analyze Segment
#### Check the frequency of:
#### Retail
#### SME
#### Corporate
#### Premium
#### Also determine whether missing values exist.
#### Then replace missing Segment values with the most appropriate category based on your
#### analysis.
#### Use: value_counts(), fillna()

In [78]:
df["Segment"].value_counts()
df["Segment"].isna().sum()
df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])
df["Segment"].value_counts()

Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

#### Q21. Clean Active
#### Active is supposed to be a binary column, but it contains:
#### Yes
#### No
#### Y
#### N
#### YES
#### NO
#### yes
#### no
#### 1
#### 0
#### Transform these into a consistent representation:
#### Yes
#### No
#### Then verify the result with value_counts().
#### Use: replace(), value_counts()

In [81]:
df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "1": "Yes",
    1: "Yes",

    "N": "No",
    "NO": "No",
    "no": "No",
    "0": "No",
    0: "No"
})

print(df["Active"].value_counts())

Active
Yes    1345
No      597
Name: count, dtype: int64

#### Q22. Clean Risk_Level
#### Check the distribution of:
#### High
#### Medium
#### Low
#### 
#### Sumit Sir Notes
#### Verify whether missing values exist.
#### Then display the final class distribution.

In [84]:
df["Risk_Level"].value_counts()

df["Risk_Level"].isna().sum()
df["Risk_Level"]

0          Low
1         High
2       Medium
3         High
4         High
         ...
1995    Medium
1996      High
1997       Low
1998       Low
1999       Low
Name: Risk_Level, Length: 2000, dtype: object

#### Q23. Rename columns
#### Rename these columns:
#### Customer_ID → Customer_ID
#### Annual_Income → AnnualIncome
#### Account_Balance → AccountBalance
#### Credit_Score → CreditScore
#### Tenure_Years → Tenure
#### Join_Date → CustomerJoinDate
#### Risk_Level → RiskLevel
#### Monthly_Spend → MonthlySpend
#### Satisfaction_Score → SatisfactionScore
#### Use rename().

In [87]:
df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

print(df.columns)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Customer_ID', 'Age', 'AnnualIncome',
       'AccountBalance', 'CreditScore', 'Tenure', 'City', 'Segment', 'Channel',
       'CustomerJoinDate', 'Active', 'RiskLevel', 'MonthlySpend',
       'Transactions', 'SatisfactionScore'],
      dtype='object')

#### Add:
#### Customer_
#### to every column.
#### Example:
#### Age
#### becomes:
#### Customer_Age
#### Use: add_prefix()

In [90]:
df = df.add_prefix("Customer_")
df

,Customer_Unnamed: 0.1,Customer_Unnamed: 0,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,0,0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,1,1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,2,2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,3,3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,4,4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
1996,1996,2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
1997,1997,2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
1998,1998,2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
1999,1999,2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

#### Q25. Remove unnecessary column
#### Determine whether Customer_ID should be retained for analysis.
#### Create a cleaned DataFrame without the identifier column.
#### Use: drop()

In [93]:
df_clean = df.drop(columns=["Customer_Customer_ID"])
df_clean

,Customer_Unnamed: 0.1,Customer_Unnamed: 0,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,0,0,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,1,1,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,2,2,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,3,3,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,4,4,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,2035,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
1996,1996,2036,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
1997,1997,2037,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
1998,1998,2038,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
1999,1999,2039,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

In [95]:
df.to_csv("Clean_Data.csv", index=False)